services:
  api:
    build: 
      context: backend/
      target: pv
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    restart: always
    networks:
      - app
    container_name: api

  ui:
    build:
      context: frontend/
      target: pv

    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
    restart: always
    networks:
      - app
    container_name: ui

networks:
  app:
    driver: bridge